export enum SongsActionTypes {
    SELECT_COLLECTION = "SONGS_SELECT_COLLECTION",
    SELECT_SONG = "SONGS_SELECT_SONG",
    SELECT_CONTRIBUTOR = "SONGS_SELECT_CONTRIBUTOR",
    TRANSPOSE = "SONGS_TRANSPOSE",
    SET_LIST = "SONGS_SET_LIST",
    INIT = "SONGS_INIT",
}
