export enum StripeMutationTypes {
    SET_PRODUCTS = "STORE_SET_PRODUCTS",
    SET_KEY = "STORE_SET_KEY",
    CART_ADD_PRODUCT = "STORE_CART_ADD_PRODUCT",
    CART_REMOVE_PRODUCT = "STORE_CART_REMOVE_PRODUCT",
    CART_CLEAR = "STORE_CART_CLEAR",
    CART_SHOW = "STORE_SHOW_CART",
    CART_SET = "STORE_CART_SET",
    CART_TYPE = "STORE_SET_TYPE",
}
